import "./globals.css";
import type { Metadata } from "next";
import Provider from "./providers";
import Topbar from "@/components/navbar";
import { Box } from "@chakra-ui/react";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "MainStack",
  description: "Generated by create next app",
};

const delugar = localFont({
  src: [
    {
      path: "fonts/Degular/Degular-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "fonts/Degular/Degular-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "fonts/Degular/Degular-Semibold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "fonts/Degular/Degular-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/favicon.png" type="image/x-icon" />
      </head>
      <body style={{ position: "relative" }} className={delugar.className}>
        <Provider>
          <Topbar />
          <Box maxW={1160} mt={"144px"} mx={"auto"}>
            {children}
          </Box>
        </Provider>
      </body>
    </html>
  );
}
